version: '3.5'
services:

    db:
        container_name: library_db
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=lappis
            - MONGO_INITDB_ROOT_PASSWORD=lappis
        ports:
            - '27017:27017'
    
 