version: '3'

services:
  db:
    container_name: library_db
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lappis
      - MONGO_INITDB_ROOT_PASSWORD=lappis
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - stack

  app:
    container_name: application
    build: .
    depends_on:
      - db

  metabase:
    container_name: metabase
    image: "metabase/metabase:latest"
    ports:
      - "3000:3000"
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - ./data/metabase:/metabase-data
    networks:
      - stack
    depends_on:
      - db

networks:
  stack:
    driver: bridge