name: CD

on:
  release:
    types: [ published ]
    
    
jobs:
  run-tests-with-poetry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup python 3.8 enviroment
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v8
      - run: poetry install
      - run: poetry build
      - run: poetry run pytest tests/
      
  publish-package:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:  
      - name: Checkout Repository  # You must checkout your repository first.
        uses: actions/checkout@v3

      - name: Publish Package
        uses: celsiusnarhwal/poetry-publish@v2
        with:
          python-version: 3.8.10
          poetry-version: 1.3.1
          username: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}

