name: CD

on:
  release:
    types: [ published ]
    
    
jobs:
  publish-service-client-package:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:  
      - name: Checkout Repository  # You must checkout your repository first.
        uses: actions/checkout@v3

      - name: Publish Package
        uses: celsiusnarhwal/poetry-publish@v2
        with:
          python-version: 3.8.10
          poetry-version: 1.3.1
          username: "__token__"
          password: "pypi-AgEIcHlwaS5vcmcCJDgyOTk4YmFiLWI5MWYtNDkwNS1iNjQwLTUwMzQyN2FmNDI1OQACKlszLCJhNGE4MDJjOC01MTZhLTQyMTktYjdlNi1hYjY2OTc2ZDc3MmEiXQAABiCkHqBWKns4HEVS-JscNc1Ic8e99pDXHHTH6rSFwsySDw"
          build: true
